WIP encrypted cookie implmetation
torrust/torrust-tracker pull request #1091
Opened 2024-11-17 12:31 UTC by da2ce7

- Tests are not finished yet.

2024-11-18 16:19 UTC, josecelano approved these changes, later dismissed
Hi @da2ce7 It looks good to me. I have only added some minor suggestions.

Regarding performance, it seems it hasn't changed.

### This PR

**Worst case**:

```
Requests out: 425928.00/second
Responses in: 403889.28/second
  - Connect responses:  199933.64
  - Announce responses: 199936.23
  - Scrape responses:   4019.41
  - Error responses:    0.00
Peers per announce response: 0.00
Announce responses per info hash:
  - p10: 1
  - p25: 1
  - p50: 1
  - p75: 1
  - p90: 2
  - p95: 3
  - p99: 105
  - p99.9: 323
  - p100: 407
```  

**Best case:**
  
```
Requests out: 492705.64/second
Responses in: 415447.68/second
  - Connect responses:  205609.94
  - Announce responses: 205718.08
  - Scrape responses:   4119.67
  - Error responses:    0.00
Peers per announce response: 0.00
Announce responses per info hash:
  - p10: 1
  - p25: 1
  - p50: 1
  - p75: 1
  - p90: 2
  - p95: 3
  - p99: 105
  - p99.9: 331
  - p100: 429
```  

### Base branch

**Worst case:**

```
Requests out: 416133.96/second
Responses in: 379643.54/second
  - Connect responses:  188013.86
  - Announce responses: 187883.50
  - Scrape responses:   3745.38
  - Error responses:    0.80
Peers per announce response: 0.00
Announce responses per info hash:
  - p10: 1
  - p25: 1
  - p50: 1
  - p75: 1
  - p90: 2
  - p95: 3
  - p99: 104
  - p99.9: 305
  - p100: 389
```  

**Best case:**

```
Requests out: 539571.74/second
Responses in: 448536.20/second
  - Connect responses:  222046.78
  - Announce responses: 222037.22
  - Scrape responses:   4452.20
  - Error responses:    0.00
Peers per announce response: 0.00
Announce responses per info hash:
  - p10: 1
  - p25: 1
  - p50: 1
  - p75: 1
  - p90: 2
  - p95: 3
  - p99: 104
  - p99.9: 353
  - p100: 455
```

2024-11-18 16:19 UTC, josecelano commented on src/bootstrap/app.rs
> +    assert_eq!(seed, instance, "maybe using zeroed see in production!?");
@da2ce7 typo here, `see` should be `seed`.

2024-11-18 16:19 UTC, josecelano commented on src/servers/udp/connection_cookie.rs
> +    }
Hi @da2ce7, since we have two other errors that also are invalid connection IDs, I would rename this error to `ConnectionIdWithInvalidIssueTime`, or `InvalidIssueTimeInConnectionId` or simply `InvalidIssueTime`.

2024-11-18 16:19 UTC, josecelano commented on src/servers/udp/connection_cookie.rs
> +pub fn check(cookie: &Cookie, fingerprint: u64, min: f64, max: f64) -> Result<f64, Error> {
Why don't you use a [range](https://doc.rust-lang.org/std/ops/struct.Range.html) here, @da2ce7, instead of the assert?

```rust
use std::ops::Range;

pub fn check(cookie: &Cookie, fingerprint: u64, range: Range<f64>) -> Result<f64, Error> {}
```

2024-11-18 16:19 UTC, josecelano commented on src/servers/udp/error.rs
> +    ConnectionIdExpired { bad_age: f64, min_age: f64 },
`expired_issue_time` instead of `bad_age`. `bad` for what or why?

2024-11-18 16:19 UTC, josecelano commented on src/servers/udp/server/processor.rs
> +        let cookie_tolerance_max_time = cookie_issue_time + 1.0;
I would wrap these three values with a new type:

```rust
struct CookieValidation {
  issue_time: f64,
  expiry_time: f64,
  tolerance_max_time: f64,
}

impl CookieValidation {
  fn new(now: f64) -> Self {
    // ...

    // cookie_expiry_time and cookie_tolerance_max_time calculated in the constrcutor
  }
}
```

2024-11-18 16:19 UTC, josecelano commented on src/servers/udp/handlers.rs
> +    }
Why don't you move this function to production code?

2024-11-19 08:21 UTC, josecelano approved these changes

2024-11-19 08:22 UTC, josecelano commented
ACK a5e8796ee1133592fcb9f143febf7f9b9fdae191

2024-11-19 08:23 UTC, josecelano requested changes
Hi @da2ce7 some tests are not passing after these latest changes.

2024-11-19 09:21 UTC, josecelano approved these changes

2024-11-19 09:21 UTC, josecelano commented on src/servers/udp/connection_cookie.rs
> +    assert!(valid_range.is_empty(), "a range should be defined");
Hi @da2ce7, maybe we can create a `NonEmptyRange`:

```rust
use std::ops::Range;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NonEmptyRange {
    start: usize,
    end: usize,
}

impl NonEmptyRange {
    /// Creates a new `NonEmptyRange` from a standard `Range` if it is non-empty.
    pub fn from_range(range: Range<usize>) -> Option<Self> {
        if range.start < range.end {
            Some(Self {
                start: range.start,
                end: range.end,
            })
        } else {
            None
        }
    }

    /// Returns the start of the range.
    pub fn start(&self) -> usize {
        self.start
    }

    /// Returns the end of the range.
    pub fn end(&self) -> usize {
        self.end
    }

    /// Returns an iterator over the range.
    pub fn iter(&self) -> impl Iterator<Item = usize> {
        self.start..self.end
    }
}
```

And refactor the param to `valid_issue_time_range: NonEmptyRange<f64>`.

2024-11-19 09:21 UTC, josecelano commented
ACK c53e2895d96b2c6c30a7d454d23f793b53fee4f1

2024-11-19 09:35 UTC, merged

2024-11-21 11:27 UTC, da2ce7 commented on src/servers/udp/connection_cookie.rs
> +    assert!(valid_range.is_empty(), "a range should be defined");
Not implemented.