Fix API bug: Torrent cannot be whitelisted twice
torrust/torrust-tracker pull request #117
Opened 2022-11-24 17:09 UTC by josecelano

- [ ] Reproduce the error with a e2e test.
- [ ] Fix it.

2022-11-24 19:00 UTC, josecelano commented
ACK 2d621c5e64f657e9be1f99af65ba8b160b9b68d0

2022-11-24 20:36 UTC, da2ce7 requested changes
You seem to be just checking if there is any error, then assuming that it isn't already inserted.

I suggest that you consider: https://github.com/torrust/torrust-tracker/pull/118

2022-11-25 10:53 UTC, josecelano commented
hi @da2ce7 @WarmBeer, I changed the implementation to send a message from the API server to the initiator when the API is ready, as we discussed yesterday. You can see the changes [here](https://github.com/torrust/torrust-tracker/pull/117/commits/32a6d79ea3c53401a14a44dede63e039330675e1).

I do not like it yet. I think we should send the message after starting the server.

I think we can do what @da2ce7 suggested. Something like:

```rust
tokio::spawn(async move {
    let (_addr, api_server) = serve(server).bind_with_graceful_shutdown(socket_addr, async move {
        tokio::signal::ctrl_c().await.expect("Failed to listen to shutdown signal.");
    });
});

// Send a message to the initiator to notify the API is ready to accept requests
if messenger_to_initiator.send(ApiReady()).is_err() {
    panic!("the receiver dropped");
}
```

@da2ce7 is that what you suggested? Using a new thread to launch the server and send the message afterwards.

I'm not sure if that's a significant change. I suppose the problem was not the time it takes the server to be ready but the fact that tests run in parallel.

2022-11-25 14:24 UTC, josecelano commented
ACK 15aa8313fde6aeb82daa563bc9bc4ca902402808

2022-11-25 15:13 UTC, da2ce7 commented on src/jobs/tracker_api.rs
> +        server::start(bind_addr, tracker).await;
What reason to send `ApiServerJobStarted()` before `server::start` has finished starting?

Maybe something like this is better:

```Rust
    let join_handle = tokio::spawn(async move {
        let handel = server::start(bind_addr, tracker);

        if tx.send(ApiServerJobStarted()).is_err() {
            panic!("the start job dropped");
        }

        handel.await
    });
```
?

2022-11-25 16:27 UTC, josecelano commented
ACK 5274b2c067aeea9d1bf344930fe7f1bdea794627

2022-11-25 17:04 UTC, da2ce7 approved these changes
ACK 5274b2c067aeea9d1bf344930fe7f1bdea794627

2022-11-25 17:05 UTC, merged