Refactor UdpClient to return errors instead of panicking
torrust/torrust-tracker pull request #814
Opened 2024-04-26 08:11 UTC by ngthhu

I replaced panics with error handling using `anyhow::Result<T>`, which is equivalent to `std::result::Result<T, anyhow::Error>`. Although I can run `cargo run` without errors, I'm not certain if there are any hidden bugs.

2024-04-26 13:05 UTC, josecelano requested changes
Hi @ngthhu thank you!! Look good. However, some workflows are failing. You can start fixing:

https://github.com/torrust/torrust-tracker/actions/runs/8845155075/job/24288517159?pr=814#step:6:800

You can run at least some commands locally before committing. For example:

**Clippy**

```console
CARGO_INCREMENTAL=0 cargo clippy --no-deps --tests --benches --examples --workspace --all-targets --all-features -- -D clippy::correctness -D clippy::suspicious -D clippy::complexity -D clippy::perf -D clippy::style -D clippy::pedantic
```

**Unit tests**

```console
cargo test
```

I would suggest installing Clippy in your IDE.

You can run all commands in the [testing](https://github.com/torrust/torrust-tracker/blob/develop/.github/workflows/testing.yaml) workflow locally.

What I do is:

1. Use Visual Studio Code with Clippy (and other extensions)
2. Run unit tests after small changes `cargo test`.
3. Run E2E tests before committing (`cargo run --bin e2e_tests_runner ./share/default/config/tracker.e2e.container.sqlite3.toml`).
Let me know if you have any trouble fixing those errors.

Regarding the new feature to test some trackers in bulk. I would do it after merging all console commands in one. See https://github.com/torrust/torrust-tracker/discussions/660

Finally, I would split this PR in two anyway:

1. One for changing the API returning an error instead of 
panicking.
2. Another to add the new feature to test a list of trackers.

2024-04-26 13:05 UTC, josecelano commented on http_trackers.sh
Hi @ngthhu, I've just started the PR review, I'm commenting on this and other things in the next minutes.

First, we favor scripting in Rust over Bash unless Bash offers crucial features or simplifies script maintenance or implementation. Se, for example:

https://github.com/torrust/torrust-tracker/blob/develop/src/bin/e2e_tests_runner.rs

The reasons are:

- It's enjoyable
- It's easier to test
- Developers can also contribute, not only sys admins. I mean, it lowers the entry barrier to maintain those scripts (in my opinion).

On the other hand, this looks like a good feature for the UDP client. It could accept both:

- A filepath to a file containing a list of trackers (trackers.txt)
- It could be passed via stdin.

```console
cargo run --bin udp_tracker_client announce --trackers="./tracker.txt" 
9c38422213e30bff212b30c360d26f9a02136422

cat ./tracker.txt cargo run --bin udp_tracker_client announce 9c38422213e30bff212b30c360d26f9a02136422
```

I have yet to think about the best option to pass that argument. I would depend on what it's the standard or best way to do it using `clap`. I will think about this and give more feedback.

2024-04-26 13:05 UTC, josecelano commented on trackers.txt
@ngthhu I would move this file to a fixtures folder (maybe `tests/fixtures/`) like this:

https://github.com/torrust/torrust-index/tree/develop/tests/fixtures/torrents

And I would rename it to `http_trackers.txt`.

Maybe we don't need to add the list to the repo. Maybe we could get an updated list from: https://newtrackon.com/. For example, for HTTP trackers:

https://newtrackon.com/api/http

We could run the test like this:

```console
curl https://newtrackon.com/api/http | cargo run --bin http_tracker_client announce 9c38422213e30bff212b30c360d26f9a02136422
```

or

```console
curl -o http_trackers.txt https://newtrackon.com/api/http
cargo run --bin http_tracker_client announce --tracker="./http_trackers.txt" 9c38422213e30bff212b30c360d26f9a02136422
```

2024-04-26 13:31 UTC, ngthhu commented
Thank you for your responses @josecelano. 

>Use Visual Studio Code with Clippy (and other extensions)
>
Currently I'm using Visual Studio Code too and I see Clippy running everytime I save a `.rs` file.

>Run unit tests after small changes cargo test.
Run E2E tests before committing (cargo run --bin e2e_tests_runner ./share/default/config/tracker.e2e.container.sqlite3.toml).
Let me know if you have any trouble fixing those errors.
>
I haven't done this before.

When I run `cargo test`, there are errors in `tests/servers/udp/contract.rs`, that file has some calls to functions in the `src/shared/bit_torrent/tracker/udp/client.rs` file that I have modified with errors, I guest I would resolve them.

I will run E2E test later then provide more info.

>Regarding the new feature to test some trackers in bulk
>

I did some test on another issue and forgot to exclude them in this pull request. I manually edited the list so it contain only http url without the `/announce` suffix.

2024-04-26 13:36 UTC, josecelano commented
> Thank you for your responses @josecelano.
> 
> > Use Visual Studio Code with Clippy (and other extensions)
> 
> Currently I'm using Visual Studio Code too and I see Clippy running everytime I save a `.rs` file.
> 

OK. Sometimes, you could have errors in workflows (but not locally) just because they started using a newer Rust version. I usually work with the updated nightly version.

> > Run unit tests after small changes cargo test.
> > Run E2E tests before committing (cargo run --bin e2e_tests_runner ./share/default/config/tracker.e2e.container.sqlite3.toml).
> > Let me know if you have any trouble fixing those errors.
> 
> I haven't done this before.
> 

You will need to setup some system dependencies like docker and other things. Let me know if docs are not clear enougth.

> When I run `cargo test`, there are errors in `tests/servers/udp/contract.rs`, that file has some calls to functions in the `src/shared/bit_torrent/tracker/udp/client.rs` file that I have modified with errors, I guest I would resolve them.
> 
> I will run E2E test later then provide more info.
> 
> > Regarding the new feature to test some trackers in bulk
> 
> I did some test on another issue and forgot to exclude them in this pull request. I manually edited the list so it contain only http url without the `/announce` suffix.

Cool! It's a nice-to-have feature. I wanted to do it just to see if the client works fine with different trackers. But I'm focused on other things now.

2024-04-26 15:28 UTC, hungfnt commented
>I will run E2E test later then provide more info.
>

I run E2E test on my wsl2 with docker and there's a permission error

```
$ cargo run --bin e2e_tests_runner ./share/default/config/tracker.e2e.container.sqlite3.toml
    Finished dev [optimized + debuginfo] target(s) in 0.47s
     Running `target/debug/e2e_tests_runner ./share/default/config/tracker.e2e.container.sqlite3.toml`
2024-04-26T20:37:06.350717686+07:00 [torrust_tracker::console::ci::e2e::runner][INFO] Reading tracker configuration from file: ./share/default/config/tracker.e2e.container.sqlite3.toml ...
2024-04-26T20:37:06.350912390+07:00 [torrust_tracker::console::ci::e2e::tracker_container][INFO] Building tracker container image with tag: torrust-tracker:local ...
ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied
thread 'main' panicked at src/console/ci/e2e/tracker_container.rs:44:55:
A tracker local docker image should be built: Custom { kind: Other, error: "Failed to build Docker image from dockerfile ./Containerfile" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-04-26T20:37:06.711867433+07:00 [torrust_tracker::console::ci::e2e::tracker_container][INFO] Dropping tracker container: tracker_tC9w2x2olkoJhbrSbJew
```

I followed this [solution](https://github.com/rancher-sandbox/rancher-desktop/issues/1156#issuecomment-1017042882), then restart docker, wsl distro and that error is fixed.

2024-04-26 15:44 UTC, josecelano commented
> > I will run E2E test later then provide more info.
> 
> I run E2E test on my wsl2 with docker and there's a permission error
> 
> ```
> $ cargo run --bin e2e_tests_runner ./share/default/config/tracker.e2e.container.sqlite3.toml
>     Finished dev [optimized + debuginfo] target(s) in 0.47s
>      Running `target/debug/e2e_tests_runner ./share/default/config/tracker.e2e.container.sqlite3.toml`
> 2024-04-26T20:37:06.350717686+07:00 [torrust_tracker::console::ci::e2e::runner][INFO] Reading tracker configuration from file: ./share/default/config/tracker.e2e.container.sqlite3.toml ...
> 2024-04-26T20:37:06.350912390+07:00 [torrust_tracker::console::ci::e2e::tracker_container][INFO] Building tracker container image with tag: torrust-tracker:local ...
> ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied
> thread 'main' panicked at src/console/ci/e2e/tracker_container.rs:44:55:
> A tracker local docker image should be built: Custom { kind: Other, error: "Failed to build Docker image from dockerfile ./Containerfile" }
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 2024-04-26T20:37:06.711867433+07:00 [torrust_tracker::console::ci::e2e::tracker_container][INFO] Dropping tracker container: tracker_tC9w2x2olkoJhbrSbJew
> ```
> 
> I followed this [solution](https://github.com/rancher-sandbox/rancher-desktop/issues/1156#issuecomment-1017042882), then restart docker, wsl distro and that error is fixed.

Hi, permissions are a very common problem with docker, unfortunately :-/. Sometimes, what I do (if I don't want to run E2E tests locally because they are very slow) is open a draft PR with just one commit while I'm working on the next commit (task increment). I check the workflow after a while to see if workflows have passed, if there is an error I fix it locally. This way, I can take advantage of both my PC and the runners :-). But sometimes, it is also slow because we are using shared runners.

Besides, if you find a problem in the future, I would suggest immediately opening an issue while you are working on fixing it. There are two advantages:

1. People with the same problem in the future are more likely to see your solution if it is an issue rather than a comment on a PR.
2. There could be someone else who can help you to fix it faster.

2024-04-26 16:15 UTC, ngthhu commented
>Sometimes, what I do (if I don't want to run E2E tests locally because they are very slow) is open a draft PR with just one commit while I'm working on the next commit (task increment).
>
They are very really slow, thank you for your method.

2024-04-27 16:05 UTC, josecelano commented
> > Sometimes, what I do (if I don't want to run E2E tests locally because they are very slow) is open a draft PR with just one commit while I'm working on the next commit (task increment).
> 
> They are very really slow, thank you for your method.

We run an isolated tracker for each test to avoid coupling between tests and because some tests need a custom tracker configuration.

Running tests only takes [14 seconds](https://github.com/torrust/torrust-tracker/actions/runs/8853473759/job/24314801313#step:5:3950). The slowest part is the docker build with Rust compilation. In this project, the integration tests are more important. E2E tests are just to check containerization. In the Index they are more important because we test a lot of behaviour that could not be tested without a running tracker (at that time).

In both the Tracker and the Index I added a lot of E2E and Integration tests because there were no tests and I had to do a lot of reactorings like web server migration. It was the only way to cover the main functionality. Now, I would like to progressively create more unit tests and fewer integration/E2E tests. It should be easier.

2024-05-02 15:03 UTC, josecelano approved these changes
Hi @ngthhu, Thank you!

In the future, you can return a `Result` in a test function:

https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html#tests-and-

I think that would make the tests more concise by removing the "matches". I don't know if it's possible in this particular case.

2024-05-02 15:04 UTC, josecelano commented
ACK effca568032eaffcdb9d3f984000b238962ce438

2024-05-02 15:07 UTC, merged

2024-05-03 06:29 UTC, ngthhu commented
Hi @josecelano, I think this pull request would resolve issue #671 as well.

2024-05-03 15:45 UTC, josecelano commented
> Hi @josecelano, I think this pull request would resolve issue #671 as well.

Hi, @ngthhu, I've replied [here](https://github.com/torrust/torrust-tracker/issues/671#issuecomment-2093272069).